# -*- coding: utf-8 -*-
"""chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RquYvgkdkCXlYApx5kjd6FLrKr7jcSOQ
"""

import os
from datetime import datetime

# Install the langchain-groq library if it's not already installed
!pip install -qqq langchain-groq

from langchain_groq import ChatGroq
from langchain_core.messages import (
    SystemMessage,
    HumanMessage,
    AIMessage
)

# 1. Configure the API Key
os.environ["GROQ_API_KEY"] = "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"

# 2. Initialize the High-Speed Groq Inference Model
llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.5
)

# 3. Establish the base behavior constraints for the model
system_prompt = SystemMessage(
    content="""
You are an AI Study Assistant.

Explain everything in simple language.
Always give examples.
If coding question comes explain code line by line.
"""
)

# 4. Initialize active short-term conversational memory
messages = [system_prompt]
history_file = "chat_history.txt"

# 5. Build/Reset the tracking file on system storage
with open(history_file, "w", encoding="utf-8") as f:
    f.write("===== CHAT HISTORY =====\n\n")

# 6. Reusable interface banner helper
def header():
    print("="*60)
    print("          AI STUDY ASSISTANT")
    print("="*60)
    print("Commands:")
    print("  help    -> Show available operations")
    print("  history -> View entire session transcripts")
    print("  clear   -> Wipe memory and clear the screen")
    print("  exit    -> Close down application link")
    print("="*60)

# Clear the screen once before starting the app interface
os.system('cls' if os.name == 'nt' else 'clear')
header()

# 7. Core Application Infinite Operational Loop
while True:

    question = input("\nYou : ").strip()

    # Prevent crash/unwanted generation on accidental blank entries
    if question == "":
        continue

    # Exit routine
    if question.lower() == "exit":
        print("\nGood Bye 😊")
        break

    # Help routine
    elif question.lower() == "help":
        print("""
Available Commands:
  help    - Show this instructional layout
  history - Print all entries logged to chat_history.txt
  clear   - Instantly wipe AI memory context and reset visual screen
  exit    - Safely break the loop execution pipeline
"""
)
        continue

    # History routine
    elif question.lower() == "history":
        print("\n--- Historical Log File Output ---")
        with open(history_file, "r", encoding="utf-8") as f:
            print(f.read())
        print("-----------------------------------")
        continue

    # Clear routine (FIXED & IMPROVED)
    elif question.lower() == "clear":
        # Fix 1: Modify the original list reference in-place to guarantee clean memory wipe
        messages.clear()
        messages.append(system_prompt)

        # Fix 2: Reset the physical tracking file on your hard drive
        with open(history_file, "w", encoding="utf-8") as f:
            f.write("===== CHAT HISTORY =====\n\n")

        # Fix 3: Physically wipe the terminal command window clean
        # Uses 'cls' if you are on Windows (nt) or 'clear' if you are on Mac/Linux
        os.system('cls' if os.name == 'nt' else 'clear')

        # Fix 4: Redraw the header layout on the clean screen
        header()
        print("\n✅ AI short-term memory completely reset!")
        print("✅ Terminal screen surface cleared!")
        continue

    # Normal Conversational Message Pipeline
    # Convert text to structured HumanMessage and insert into historical list tracking
    messages.append(HumanMessage(content=question))

    # Send full conversation window out to Groq for text processing
    response = llm.invoke(messages)
    answer = response.content

    # Cache AI's response text internally so it remembers its answers next turn
    messages.append(AIMessage(content=answer))

    current_time = datetime.now().strftime("%H:%M:%S")

    print(f"\nTime : {current_time}\n")
    print(f"AI :\n{answer}\n")

    # Append current question/answer transaction block down into text records
    with open(history_file, "a", encoding="utf-8") as f:
        f.write(f"\nTime : {current_time}\n")
        f.write(f"You : {question}\n")
        f.write(f"AI : {answer}\n")
        f.write("-" * 60 + "\n")